site_name: Arkpy Docs
theme: readthedocs
repo_url: https://github.com/DerekRies/arkpy
extra_css:
  - extra.css
pages:
 - Home: 'index.md'
 - User Guide: 'userguide.md'
 - Tutorials: 'tutorials.md'
 - API Documentation:
    - arktypes module: 'arktypesmodule.md'
    - ark module: 'arkmodule.md'
    - entities module: 'entities.md'
 - File Format Specs: 'formats.md'
 - Contributors Guide: 'contribs.md'
markdown_extensions:
 - admonition